/*
 * generated by Xtext 2.36.0
 */
package org.xtext.example.mindstormsdsl.ide;


/**
 * Use this class to register ide components.
 */
public class MyDslIdeModule extends AbstractMyDslIdeModule {
}
