/*
 * generated by Xtext 2.36.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getDBAccess().getGroup(), "rule__DB__Group__0");
			builder.put(grammarAccess.getDBAccess().getGroup_4(), "rule__DB__Group_4__0");
			builder.put(grammarAccess.getDBAccess().getGroup_4_3(), "rule__DB__Group_4_3__0");
			builder.put(grammarAccess.getTableAccess().getGroup(), "rule__Table__Group__0");
			builder.put(grammarAccess.getTableAccess().getGroup_4(), "rule__Table__Group_4__0");
			builder.put(grammarAccess.getTableAccess().getGroup_4_3(), "rule__Table__Group_4_3__0");
			builder.put(grammarAccess.getColumnAccess().getGroup(), "rule__Column__Group__0");
			builder.put(grammarAccess.getColumnAccess().getGroup_4(), "rule__Column__Group_4__0");
			builder.put(grammarAccess.getDBAccess().getNameAssignment_2(), "rule__DB__NameAssignment_2");
			builder.put(grammarAccess.getDBAccess().getTablesAssignment_4_2(), "rule__DB__TablesAssignment_4_2");
			builder.put(grammarAccess.getDBAccess().getTablesAssignment_4_3_1(), "rule__DB__TablesAssignment_4_3_1");
			builder.put(grammarAccess.getTableAccess().getNameAssignment_2(), "rule__Table__NameAssignment_2");
			builder.put(grammarAccess.getTableAccess().getColumnsAssignment_4_2(), "rule__Table__ColumnsAssignment_4_2");
			builder.put(grammarAccess.getTableAccess().getColumnsAssignment_4_3_1(), "rule__Table__ColumnsAssignment_4_3_1");
			builder.put(grammarAccess.getColumnAccess().getNameAssignment_2(), "rule__Column__NameAssignment_2");
			builder.put(grammarAccess.getColumnAccess().getTypeAssignment_4_1(), "rule__Column__TypeAssignment_4_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
