/*
 * generated by Xtext 2.36.0
 */
package org.xtext.example.mindstormsdsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.mindstorms.ui.internal.MindstormsActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MindstormsActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MindstormsActivator activator = MindstormsActivator.getInstance();
		return activator != null ? activator.getInjector(MindstormsActivator.ORG_XTEXT_EXAMPLE_MINDSTORMSDSL_MYDSL) : null;
	}

}
