/*
 * generated by Xtext 2.36.0
 */
package org.xtext.example.mindstormsdsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.mindstorms.ui.internal.MindstormsActivator;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MindstormsActivator.getInstance().getInjector("org.xtext.example.mindstormsdsl.MyDsl");
	}

}
