/*
 * generated by Xtext 2.36.0
 */
package org.xtext.example.mindstormsdsl.formatting2

import com.google.inject.Inject
import mindstorms.Choreography
import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument
import org.xtext.example.mindstormsdsl.services.MyDslGrammarAccess

class MyDslFormatter extends AbstractFormatter2 {
	
	@Inject extension MyDslGrammarAccess

	def dispatch void format(Choreography choreography, extension IFormattableDocument document) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (instruction : choreography.instructions) {
			instruction.format
		}
	}
	
}
