/*
 * generated by Xtext 2.36.0
 */
package org.xtext.example.mindstormsdsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mindstormsdsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mindstormsdsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getInstructionAccess().getAlternatives(), "rule__Instruction__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getChoreographyAccess().getGroup(), "rule__Choreography__Group__0");
			builder.put(grammarAccess.getChoreographyAccess().getGroup_4(), "rule__Choreography__Group_4__0");
			builder.put(grammarAccess.getChoreographyAccess().getGroup_4_3(), "rule__Choreography__Group_4_3__0");
			builder.put(grammarAccess.getGrabAccess().getGroup(), "rule__Grab__Group__0");
			builder.put(grammarAccess.getReleaseAccess().getGroup(), "rule__Release__Group__0");
			builder.put(grammarAccess.getRotateAccess().getGroup(), "rule__Rotate__Group__0");
			builder.put(grammarAccess.getRotateAccess().getGroup_4(), "rule__Rotate__Group_4__0");
			builder.put(grammarAccess.getGoForwardAccess().getGroup(), "rule__GoForward__Group__0");
			builder.put(grammarAccess.getGoForwardAccess().getGroup_3(), "rule__GoForward__Group_3__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getChoreographyAccess().getNameAssignment_2(), "rule__Choreography__NameAssignment_2");
			builder.put(grammarAccess.getChoreographyAccess().getInstructionsAssignment_4_2(), "rule__Choreography__InstructionsAssignment_4_2");
			builder.put(grammarAccess.getChoreographyAccess().getInstructionsAssignment_4_3_1(), "rule__Choreography__InstructionsAssignment_4_3_1");
			builder.put(grammarAccess.getRotateAccess().getRandomAssignment_1(), "rule__Rotate__RandomAssignment_1");
			builder.put(grammarAccess.getRotateAccess().getDegreesAssignment_4_1(), "rule__Rotate__DegreesAssignment_4_1");
			builder.put(grammarAccess.getGoForwardAccess().getCmAssignment_3_1(), "rule__GoForward__CmAssignment_3_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
